### ISSUE TITLE
Prevent gulp stopping when errors are found

### ISSUE THREAD

**Issue by brunorios1** [LiveSafe/gulp-html5-lint#3]
When the html5-lint task found an error, gulp stops the execution of a watch task.
Can we prevent this?
Thanks!

**Comment by mike-spainhower** [comment]
Sure thing, let me look into how other linters handle this case.

**Comment by mike-spainhower** [comment]
From what I can tell this shouldn't happen.  Could you paste in how your watch and lint tasks are set up so I can repro?  Thanks.

**Comment by brunorios1** [comment]
Hi @mike-spainhower, 
you are right!

I tried to reproduce the error in a clean project and it didn't happen.

But I found my mistake, I was forgetting the "return" before gulp.scr:

```
gulp.task('html5-lint', function() {
  gulp.src('*.html')
    .pipe(html5Lint());
});
```

Thanks!

**Comment by mike-spainhower** [comment]
Hah, ya, I forget those `return`s all the time.  Need a linter specially made for `gulpfile`s, lol.

I will close this issue now.
