### ISSUE TITLE
Check html-lint API is up before running

### ISSUE THREAD

**Issue by SpainTrain** [LiveSafe/gulp-html5-lint#5]
Do a check to ensure the mozilla html lint API is up before invoking linting.  See also #4

**Comment by rstoenescu** [comment]
Can this be assigned to me? I'm gonna take a shot at it. Thanks.

**Comment by rstoenescu** [comment]
Please check the PR. Thanks!

**Comment by mike-spainhower** [comment]
This has dropped in 1.1.0 (https://travis-ci.org/LiveSafe/gulp-html5-lint/jobs/89682175#L237)

Thanks again @rstoenescu
